feat: 블루/그린 배포파일 생성

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -28,8 +28,25 @@ jobs:
           java-version: '11'
           distribution: "adopt"
 
-      # create application.yml
-      - name: make application-aws.yml
+      # application-secret.yml생성
+      - name: make application-secret.yml
+        if: github.ref == 'refs/heads/main'
+        run: |
+          # spring의 resources 경로로 이동
+          cd ./src/main/resources
+          
+          # 해당 디렉토리에 application-secret.yml 파일이 이미 존재하는지 확인하고, 없으면 생성합니다.
+          if [ ! -f application-secret.yml ]; then
+          touch ./application-secret.yml
+          fi
+          
+          # GitHub Actions에서 설정한 값을 base64 디코딩하여 application-secret.yml 파일에 쓰기
+          echo "copy properties"
+          echo "${{ secrets.APPLICATION_SECRET }}" | base64 --decode > ./application-secret.yml
+        shell: bash
+
+      # application.yml생성
+      - name: make application.yml
         if: github.ref == 'refs/heads/main'
         run: |
           # spring의 resources 경로로 이동
@@ -44,6 +61,23 @@ jobs:
           echo "copy properties"
           echo "${{ secrets.MAKE_APPLICATION }}" | base64 --decode > ./application.yml
         shell: bash
+
+#      # create application.yml
+#      - name: make application-aws.yml
+#        if: github.ref == 'refs/heads/main'
+#        run: |
+#          # spring의 resources 경로로 이동
+#          cd ./src/main/resources
+#
+#          # 해당 디렉토리에 application.yml 파일이 이미 존재하는지 확인하고, 없으면 생성합니다.
+#          if [ ! -f application.yml ]; then
+#          touch ./application.yml
+#          fi
+#
+#          # GitHub Actions에서 설정한 값을 base64 디코딩하여 application.yml 파일에 쓰기
+#          echo "copy properties"
+#          echo "${{ secrets.MAKE_APPLICATION }}" | base64 --decode > ./application.yml
+#        shell: bash
 
       # gradle을 통해 소스를 빌드.
       - name: Build with Gradle
@@ -76,18 +110,88 @@ jobs:
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/spring-image:latest
 
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set target IP
+        run: |
+          STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.EC2_IP }}/api/env")
+          echo $STATUS
+          if [ $STATUS = 200 ]; then
+            CURRENT_UPSTREAM=$(curl -s "http://${{ secrets.EC2_IP }}/api/env")
+          else
+            CURRENT_UPSTREAM=green
+          fi
+          echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
+          if [ $CURRENT_UPSTREAM = blue ]; then
+            echo "CURRENT_PORT=8080" >> $GITHUB_ENV
+            echo "STOPPED_PORT=8081" >> $GITHUB_ENV
+            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
+          elif [ $CURRENT_UPSTREAM = green ]; then
+            echo "CURRENT_PORT=8081" >> $GITHUB_ENV
+            echo "STOPPED_PORT=8080" >> $GITHUB_ENV
+            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
+          else
+            echo "error"
+            exit 1
+          fi
 
-      - name: Pull and restart Docker Container
+      - name: Docker compose
         uses: appleboy/ssh-action@master
         with:
-          key: ${{ secrets.EC2_KEY }}
-          host: ${{ secrets.EC2_IP }}
           username: ubuntu
-          script:
-            docker container stop spring-image;
-            docker image rm ${{ secrets.DOCKER_USERNAME }}/spring-image;
-            docker pull ${{ secrets.DOCKER_USERNAME }}/spring-image:latest;
-            docker run -d --rm --name spring-image -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/spring-image:latest;
+          host: ${{ secrets.EC2_IP }}
+          key: ${{ secrets.EC2_KEY }}
+          script_stop: true
+          script: |
+            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/spring-image:latest
+            sudo docker-compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d
+
+      - name: Check deploy server URL
+        uses: jtalk/url-health-check-action@v3
+        with:
+          url: http://${{ secrets.EC2_IP }}:${{env.STOPPED_PORT}}/env
+          max-attempts: 3
+          retry-delay: 10s
+
+      - name: Change nginx upstream
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ secrets.EC2_IP }}
+          key: ${{ secrets.EC2_KEY }}
+          script_stop: true
+          script: |
+            sudo docker exec -i nginxserver bash -c 'echo "set \$service_url ${{ env.TARGET_UPSTREAM }};" > /etc/nginx/conf.d/service-env.inc && nginx -s reload' 
+
+      - name: Stop current server
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ secrets.EC2_IP }}
+          key: ${{ secrets.EC2_KEY }}
+          script_stop: true
+          script: |
+            sudo docker stop ${{env.CURRENT_UPSTREAM}}
+            sudo docker rm ${{env.CURRENT_UPSTREAM}}
+
+
+#      - name: Pull and restart Docker Container
+#        uses: appleboy/ssh-action@master
+#        with:
+#          key: ${{ secrets.EC2_KEY }}
+#          host: ${{ secrets.EC2_IP }}
+#          username: ubuntu
+#          script:
+#            docker container stop spring-image;
+#            docker image rm ${{ secrets.DOCKER_USERNAME }}/spring-image;
+#            docker pull ${{ secrets.DOCKER_USERNAME }}/spring-image:latest;
+#            docker run -d --rm --name spring-image -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/spring-image:latest;
+#
+
+
+
 
 
 
